kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx-deployment
  namespace: my-nginx
spec:
  replicas: 3
  selector: 
    matchLabels:
      app: nginx-pod


  template:
    metadata:
      name: nginx-dep-pod
      labels:
        app: nginx-pod


    spec:
      containers:
        - name : nginx-container
          image: nginx:latest
          ports:
            - containerPort: 80
    
